database: dev
schema: public
table: company_config
load_type: full
increment_column: 
pk: ['id']
source:
  schema: public
  table: company_config
target:
  schema: mock
  table: company_config
map:
  -
    source: id
    target: id
  -
    source: "name"
    target: "name"
  -
    source: human_name
    target: human_name
  -
    source: value
    target: value