database: dev
schema: mock
table: product_transactions
load_type: increment
increment_column: date
pk: ['id']
map:
  -
    source: id
  -
    source: product_id
  -
    source: office_id
  -
    source: doctor_id
  -
    source: patient_id
  -
    source: user_id
  -
    source: type
  -
    source: qty
  -
    source: price
  -
    source: price_per
  -
    source: total_price
  -
    source: date
  -
    source: note
  -
    source: transfer_direction
  -
    source: qty_free
  -
    source: product_checkin_id
  -
    source: product_name
  -
    source: office_to_id
  -
    source: product_to_id
  -
    source: product_to_name
  -
    source: cost
  -
    source: order_id
  -
    source: base_weight
  -
    source: product_checkin_to_id
  -
    source: office_name
