database: dev
schema: public
table: products
load_type: increment_with_delete
increment_column: sync_updated_at
pk: ['prod_id']
source:
  schema: public
  table: products
target:
  schema: mock
  table: products
map:
  -
    source: prod_id
    target: prod_id
  -
    source: prod_name
    target: prod_name
  -
    source: prod_price
    target: prod_price
  -
    source: prod_qty_w
    target: prod_qty_w
  -
    source: prod_joints_qty_w
    target: prod_joints_qty_w
  -
    source: prod_qty_o
    target: prod_qty_o
  -
    source: prod_joints_qty_o
    target: prod_joints_qty_o
  -
    source: prod_vendor_id
    target: prod_vendor_id
  -
    source: prod_category_id
    target: prod_category_id
  -
    source: prod_photo
    target: prod_photo
  -
    source: prod_price_type
    target: prod_price_type
  -
    source: prod_is_taxable
    target: prod_is_taxable
  -
    source: prod_symbol
    target: prod_symbol
  -
    source: cast(prod_gram_prepack_qty_w as BIGINT) as prod_gram_prepack_qty_w
    target: cast(prod_gram_prepack_qty_w as BIGINT) as prod_gram_prepack_qty_w
  -
    source: prod_eighth_prepack_qty_w
    target: prod_eighth_prepack_qty_w
  -
    source: prod_quarter_prepack_qty_w
    target: prod_quarter_prepack_qty_w
  -
    source: prod_half_prepack_qty_w
    target: prod_half_prepack_qty_w
  -
    source: prod_ounce_prepack_qty_w
    target: prod_ounce_prepack_qty_w
  -
    source: prod_gram_prepack_qty_o
    target: prod_gram_prepack_qty_o
  -
    source: prod_eighth_prepack_qty_o
    target: prod_eighth_prepack_qty_o
  -
    source: prod_quarter_prepack_qty_o
    target: prod_quarter_prepack_qty_o
  -
    source: prod_half_prepack_qty_o
    target: prod_half_prepack_qty_o
  -
    source: prod_ounce_prepack_qty_o
    target: prod_ounce_prepack_qty_o
  -
    source: prod_tax_id_bak
    target: prod_tax_id_bak
  -
    source: prod_is_tax_included
    target: prod_is_tax_included
  -
    source: prod_joint_cost
    target: prod_joint_cost
  -
    source: prod_is_on_shop
    target: prod_is_on_shop
  -
    source: prod_is_free_shipping
    target: prod_is_free_shipping
  -
    source: sync_updated_at
    target: sync_updated_at
  -
    source: sync_created_at
    target: sync_created_at
  -
    source: prod_balance
    target: prod_balance
  -
    source: prod_is_on_weedmaps
    target: prod_is_on_weedmaps
  -
    source: prod_is_custom_price
    target: prod_is_custom_price
  -
    source: prod_backend_product_id
    target: prod_backend_product_id
  -
    source: prod_tax_profile_id
    target: prod_tax_profile_id
  -
    source: deleted_at
    target: deleted_at
  -
    source: prod_price_preset_id
    target: prod_price_preset_id
  -
    source: prod_lab_type
    target: prod_lab_type
  -
    source: prod_is_print_label
    target: prod_is_print_label
  -
    source: lab_result_id
    target: lab_result_id
  -
    source: prod_sku
    target: prod_sku
  -
    source: prod_tv_photo
    target: prod_tv_photo
  -
    source: prod_is_hidden
    target: prod_is_hidden
  -
    source: strain
    target: strain
  -
    source: potify_id
    target: potify_id
  -
    source: is_marijuana_product
    target: is_marijuana_product
  -
    source: marijuana_product_type
    target: marijuana_product_type
  -
    source: prod_is_excise
    target: prod_is_excise
  -
    source: is_metrc
    target: is_metrc
  -
    source: is_metrc_compliant
    target: is_metrc_compliant
  -
    source: is_only_each
    target: is_only_each
  -
    source: net_weight
    target: net_weight
  -
    source: net_weight_measure
    target: net_weight_measure
  -
    source: show_on_leafly
    target: show_on_leafly
  -
    source: is_preroll
    target: is_preroll
  -
    source: preroll_weight
    target: preroll_weight
  -
    source: product_type_id
    target: product_type_id
  -
    source: prod_upc
    target: prod_upc
  -
    source: is_tax_exempt
    target: is_tax_exempt
  -
    source: cast(is_under_package_control as boolean) as is_under_package_control
    target: cast(is_under_package_control as boolean) as is_under_package_control
  -
    source: directions
    target: directions
  -
    source: twcc
    target: twcc
  -
    source: product_class
    target: product_class
  -
    source: brand_id
    target: brand_id
  -
    source: potify_brand_product_id
    target: potify_brand_product_id
  -
    source: wm_product_id
    target: wm_product_id
  -
    source: brand_product_strain_name
    target: brand_product_strain_name
  -
    source: prod_tax_tier_version_id
    target: prod_tax_tier_version_id
  -
    source: is_city_local_tax_exempt
    target: is_city_local_tax_exempt
  -
    source: brutto_weight
    target: brutto_weight
  -
    source: brutto_weight_validation
    target: brutto_weight_validation
  -
    source: custom_cost
    target: custom_cost